#%RAML 0.8

title: Account System API
baseUri: http://sfs-api-sys-account.cloudhub.io/api
version: 1.0
schemas: 
  - loan-account: !include api-sys-account-schema.json

/account:
  post: 
    body:   
      application/json: 
        schema: loan-account
        example: !include api-sys-account-example.json
        
    responses: 
      200:
        body: 
          application/json: 
            schema: loan-account
            example: !include api-sys-account-example.json