#%RAML 1.0 NamedExample
value:
  authorization: approved
  firstName: James
  middleInitial: C
  lastName: Johnson
  individualTaxNumber: 333-22-1234
  address:
    address1: 123 Main Street
    city: Madison
    state: WI
    zipCode: "54500"
  monthlyNetIncome: 6000
  combinedFicoScore: 751
  bureauScores: 
    - #item 1
      bureau: transunion
      ficoScore: 747
    - #item 2
      bureau: experian
      ficoScore: 753
    - #item 3
      bureau: equifax
      ficoScore: 750