#%RAML 0.8

title: Underwrite Loan Experience API
baseUri: http://www.mythicalfinance.com/api/exp/underwrite
version: 1.0

/applications:
  get:
    responses: 
      200: 
        body: 
          application/json: 
            schema: !include api-exp-underwrite-loan-apps-schema.json
            example: !include api-exp-underwrite-loan-apps-example.json

/decison:
  /{loan_application_id}:
    uriParameters: 
      loan_application_id:
        required: true
        type: string
        
    post: 
      responses: 
        200: 
          body: 
            application/json:
              schema: !include api-exp-underwrite-loan-decision-schema.json
              example: !include api-exp-underwrite-loan-decision-example.json