#%RAML 0.8

title: Credit Decision Process API
baseUri: http://sfs-api-proc-credit-decision.cloudhub.io/api

/decision:
  post:
    queryParameters: 
      scoreType:
        required: true
        enum: [hard, soft]
    body: 
      application/json:
        example: !include api-proc-credit-decision-example-in.json
        schema: !include api-proc-credit-decision-schema-in.json
    responses: 
      200: 
        body: 
          application/json: 
            example: !include api-proc-credit-decision-example-out.json
            schema: !include api-proc-credit-decision-schema-out.json
