#%RAML 0.8

title: Loand Application System API
baseUri: http://www.mythicalfinance.com/api/sys/application

schemas:
  - loan_app_in: !include loan-application-schema-in.json
    loan_app_out: !include loan-application-schema-out.json
    loan_apps_out: !include loan-applications-schema-out.json
    
/application:
  post: 
    body: 
      application/json: 
        example: !include loan-application-example-in.json
        schema: loan_app_in
        
    responses: 
      200:
        body: 
          application/json: 
            example: !include loan-application-example-out.json
            schema: loan_app_out
            
  /{loanId}:
    get: 
      responses: 
        200:
          body: 
            application/json: 
              example: !include loan-application-example-out.json
              schema: loan_app_out
             
/applications:
  get:
    responses:
      200:
        body: 
          application/json:
            schema: loan_apps_out  